version: "3.3"
services:
  api:
    image: docker-registry.tryflok.com/flok-api-staging:latest
    ports:
      - 8080:8080 # for websocket
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=7200
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Africa/Lagos
    links:
      - redis
    volumes:
      - ./:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
      - ./flok_worker.conf:/etc/supervisor/conf.d/flok_worker.conf
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  cron:
    image: docker-registry.tryflok.com/flok-api-cron-staging:latest
    volumes:
      - ./:/var/www
    links:
      - redis
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=3600
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Africa/Lagos

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
     - 8000:80
    links:
      - api
    volumes:
      - ./:/var/www
      - ./additional.conf:/etc/nginx/conf.d/additional.conf
      - ./flok.conf:/etc/nginx/conf.d/flok.conf
      
  redis:
    image: redis:3.0