version: "3.3"
services:
  api:
    image: docker-registry.tryflok.com/flok-api-staging:latest
    ports:
      - 8080:8080 # for websocket
      - 8000:80
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=7200
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Africa/Lagos
    links:
      - redis

  redis:
    image: redis:3.0