version: "3.3"
services:
  api:
    build: 
      args:
        user: flok
        uid: 1000
      context: ./
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 8000:80
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=7200
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Africa/Lagos
    links:
      - redis
      - mysql

  mysql:
    image: mysql:5.7.12
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - '9099:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flok

  redis:
    image: redis:3.0

  redis-local:
    image: redis:3.0